package com.sample;
 
import com.sample.DroolsTest.Plec;
import com.sample.DroolsTest.Relacja;
import com.sample.DroolsTest.Osoba;
 
rule "Init"
	when
	then	
		Osoba maria          = new Osoba("Maria");
		Osoba ewa            = new Osoba("Ewa");
		Osoba agata          = new Osoba("Agata");
		Osoba anna           = new Osoba("Anna");
		Osoba agnieszka      = new Osoba("Agnieszka");
		Osoba beata          = new Osoba("Beata");
		Osoba iwona          = new Osoba("Iwona");
		Osoba joanna         = new Osoba("Joanna");
		Osoba piotr          = new Osoba("Piotr");
		Osoba adam           = new Osoba("Adam");
		Osoba marek          = new Osoba("Marek");
		Osoba robert         = new Osoba("Robert");
		Osoba jan            = new Osoba("Jan");
		Osoba krzysztof      = new Osoba("Krzysztof");
		Osoba radek          = new Osoba("Radek");
		Osoba darek          = new Osoba("Darek");
		Osoba tomek          = new Osoba("Tomek");
		Osoba jacek          = new Osoba("Jacek");

		insert(new Relacja(maria,marek,"rodzic"));
		insert(new Relacja(maria,agata,"rodzic"));
		insert(new Relacja(maria,jan,"rodzic"));
		insert(new Relacja(piotr,marek,"rodzic"));
		insert(new Relacja(piotr,agata,"rodzic"));
		insert(new Relacja(piotr,jan,"rodzic"));
		insert(new Relacja(ewa,anna,"rodzic"));
		insert(new Relacja(ewa,joanna,"rodzic"));
		insert(new Relacja(ewa,krzysztof,"rodzic"));
		insert(new Relacja(adam,anna,"rodzic"));
		insert(new Relacja(adam,joanna,"rodzic"));
		insert(new Relacja(adam,krzysztof,"rodzic"));
		insert(new Relacja(agata,radek,"rodzic"));
		insert(new Relacja(agata,beata,"rodzic"));
		insert(new Relacja(robert,radek,"rodzic"));
		insert(new Relacja(robert,beata,"rodzic"));
		insert(new Relacja(anna,darek,"rodzic"));
		insert(new Relacja(anna,tomek,"rodzic"));
		insert(new Relacja(jan,darek,"rodzic"));
		insert(new Relacja(jan,tomek,"rodzic"));
		insert(new Relacja(agnieszka,jacek,"rodzic"));
		insert(new Relacja(agnieszka,iwona,"rodzic"));
		insert(new Relacja(krzysztof,jacek,"rodzic"));
		insert(new Relacja(krzysztof,iwona,"rodzic"));

end

rule "Rozpoznaj_plec"
    when
        r : Relacja( osoby[0].plec == Plec.NIEZNANA || osoby[1].plec == Plec.NIEZNANA)
    then
    	for (int i = 0; i < 2; i++)
    	{
    		if ( r.osoby[i].plec == Plec.NIEZNANA)
    		{
		    	if ( r.osoby[i].imie.endsWith("a") == true )
		    	{
		    		System.out.println( "true" );
		    		System.out.println( "  " + r.osoby[i].imie );
		    		r.osoby[i].plec = Plec.KOBIETA;
		    	//	if (exists Relacja( osoby[0].imie == r.osoby[i].imie || osoby[1].imie == r.osoby[i].imie ) )
		    //		{
		    		update( r );
		    //		}
		    	}	
		    	else
		    	{
		    	    System.out.println( "false" );
		    	    System.out.println( "  " + r.osoby[i].imie );
		    		r.osoby[i].plec = Plec.MEZCZYZNA;
		    		update( r );
		    		
		    	}
		    }
    	}
end

rule "ojciec_matka"
	when
		r : Relacja( relacja == "rodzic" )
	then
	    if ( r.osoby[0].plec == Plec.KOBIETA )
	   	{
	   		System.out.println( "matka" );
		  	System.out.println( "  " + r.osoby[0].imie );
	   		insert(new Relacja( r.osoby[0], r.osoby[1], "matka") );
		}	
	   	else
    	{
	    	System.out.println( "ojciec" );
		    System.out.println( "  " + r.osoby[0].imie );
		  	insert(new Relacja( r.osoby[0], r.osoby[1], "ojciec") );		
		}
end

rule "babcia_dziadek"
	when
		r : Relacja( relacja == "matka" || relacja == "ojciec" )
	then
	    if ( r.osoby[0].plec == Plec.KOBIETA )
	   	{
	   		System.out.println( "matka" );
		  	System.out.println( "  " + r.osoby[0].imie );
	   		insert(new Relacja( r.osoby[0], r.osoby[1], "matka") );
		}	
	   	else
    	{
	    	System.out.println( "ojciec" );
		    System.out.println( "  " + r.osoby[0].imie );
		  	insert(new Relacja( r.osoby[0], r.osoby[1], "ojciec") );		
		}
end


