package com.sample;

import javax.swing.JFrame;
import com.sample.MyFrame.Answer;

global MyFrame frame;
 
declare Question
	question : String
	answer : String
end

rule "answer"
	when
		a : Answer() && q : Question()
		
	then
		q.setAnswer(a.getAnswer());
		update(q);
		delete(a);
		System.out.println(q.getAnswer());
end

rule "Is a train going into a tunel ever just a train going into a tunel?"
	when
	then
		String questiontext = "Is a train going into a tunel ever just a train going into a tunel?";
		String answer1 = "Of course it's just a train going into a tunel. What else would it be?";
		String answer2 = "No. It's always sexual and Freudian.";
		String answer3 = "";
		
		Question question = new Question();
		question.setQuestion(questiontext);
		insert(question);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);
		frame.pack();
end
 
rule "Alfred Hitchcock"
	when
		q : Question(question == "Is a train going into a tunel ever just a train going into a tunel?" , answer=="No. It's always sexual and Freudian.")
	then
		String questiontext = "Alfred Hiczkok";;
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you like your movies a little on the creepy side?"
	when
		q : Question(question == "Is a train going into a tunel ever just a train going into a tunel?" , answer=="Of course it's just a train going into a tunel. What else would it be?")
	then
		String questiontext = "Do you like your movies a little on the creepy side?";
		String answer1 = "No creepiness for me. it's not important";
		String answer2 = "Yes, but only a little.";
		String answer3 = "I love creepy movies.";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

//lewo

rule "Give me something that that's..."
	when
		q : Question(question == "Do you like your movies a little on the creepy side?" , answer=="No creepiness for me. it's not important")
	then
		String questiontext = "Give me something that that's...";
		String answer1 = "A comedy";
		String answer2 = "An action movie";
		String answer3 = "A drama";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Did you light ants on fire when you were a kid and yell \"BOOM!\" when they lit on fire?"
	when
		q : Question(question == "Give me something that that's..." , answer=="An action movie")
	then
		String questiontext = "Did you light ants on fire when you were a kid and yell \"BOOM!\" when they lit on fire?";
		String answer1 = "Yep.";
		String answer2 = "No. What kind of simpleton would do that?";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Michael Bay"
	when
		q : Question(question == "Did you light ants on fire when you were a kid and yell \"BOOM!\" when they lit on fire?" , answer=="Yep.")
	then
		String questiontext = "Michael Bay";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "What is most important to you in an action movie?"
	when
		q : Question(question == "Did you light ants on fire when you were a kid and yell \"BOOM!\" when they lit on fire?" , answer=="No. What kind of simpleton would do that?")
	then
		String questiontext = "What is most important to you in an action movie?";
		String answer1 = "Blood.";
		String answer2 = "Fantasy.";
		String answer3 = "Heavy plot.";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Sam Peckinpah"
	when
		q : Question(question == "What is most important to you in an action movie?" , answer=="Blood.")
	then
		String questiontext = "Sam Peckinpah";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Peter Jackson"
	when
		q : Question(question == "What is most important to you in an action movie?" , answer=="Fantasy.")
	then
		String questiontext = "Peter Jackson";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Christopher Nolan"
	when
		q : Question(question == "What is most important to you in an action movie?" , answer=="Heavy plot.")
	then
		String questiontext = "Christopher Nolan";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "How do you feel about Jonah Hill?"
	when
		q : Question(question == "Give me something that that's..." , answer=="A comedy")
	then
		String questiontext = "How do you feel about Jonah Hill?";
		String answer1 = "He is not a comic genius.";
		String answer2 = "He is a comic genius.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Judd Apatow"
	when
		q : Question(question == "How do you feel about Jonah Hill?" , answer=="He is a comic genius.")
	then
		String questiontext = "Judd Apatow";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you prefer quirky or gross-out comedies?"
	when
		q : Question(question == "How do you feel about Jonah Hill?" , answer=="He is not a comic genius.")
	then
		String questiontext = "Do you prefer quirky or gross-out comedies?";
		String answer1 = "Gross stuff is hilarious.";
		String answer2 = "I like 'em quirky and...";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "I like 'em quirky and..."
	when
		q : Question(question == "Do you prefer quirky or gross-out comedies?" , answer=="I like 'em quirky and...")
	then
		String questiontext = "I like 'em quirky and...";
		String answer1 = "dark. Darker than a black steer's tookus on a moonless prairie night";
		String answer2 = "I kind of hate my dad.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "The Coen Brothers"
	when
		q : Question(question == "I like 'em quirky and..." , answer=="dark. Darker than a black steer's tookus on a moonless prairie night")
	then
		String questiontext = "The Coen Brothers";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Wes Anderson"
	when
		q : Question(question == "I like 'em quirky and..." , answer=="I kind of hate my dad.")
	then
		String questiontext = "Wes Anderson";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you want gross stuff with stoners or without?"
	when
		q : Question(question == "Do you prefer quirky or gross-out comedies?" , answer=="Gross stuff is hilarious.")
	then
		String questiontext = "Do you want gross stuff with stoners or without?";
		String answer1 = "With";
		String answer2 = "Without";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Kevin Smith"
	when
		q : Question(question == "Do you want gross stuff with stoners or without?" , answer=="With")
	then
		String questiontext = "Kevin Smith";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "The Farrelly Brothers"
	when
		q : Question(question == "Do you want gross stuff with stoners or without?" , answer=="Without")
	then
		String questiontext = "The Farrelly Brothers";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Yes, but only a little. Preferably..."
	when
		q : Question(question == "Do you like your movies a little on the creepy side?" , answer=="Yes, but only a little.")
	then
		String questiontext = "Yes, but only a little. Preferably...";
		String answer1 = "shrouded in the comfort of a big blockbuster.";
		String answer2 = "I want my movies to make me feel uncomfortable";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Darren Aronofsky"
	when
		q : Question(question == "Yes, but only a little. Preferably..." , answer=="I want my movies to make me feel uncomfortable")
	then
		String questiontext = "Darren Aronofsky";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "How do you feel about lens flares and dumbstruck faces looking off camera?"
	when
		q : Question(question == "Yes, but only a little. Preferably..." , answer=="shrouded in the comfort of a big blockbuster.")
	then
		String questiontext = "How do you feel about lens flares and dumbstruck faces looking off camera?";
		String answer1 = "They're awesome!";
		String answer2 = "Who the hell cares?";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Steven Spielberg"
	when
		q : Question(question == "How do you feel about lens flares and dumbstruck faces looking off camera?" , answer=="They're awesome!")
	then
		String questiontext = "Steven Spielberg";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "James Cameron"
	when
		q : Question(question == "How do you feel about lens flares and dumbstruck faces looking off camera?" , answer=="Who the hell cares?")
	then
		String questiontext = "James Cameron";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "How do you feel about foreign directors?"
	when
		q : Question(question == "Give me something that that's..." , answer=="A drama")
	then
		String questiontext = "How do you feel about foreign directors?";
		String answer1 = "I love them.";
		String answer2 = "I said I wanted to watch drama. Don't get carried away.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end



rule "Lars Von Trier"
	when
		q : Question(question == "What's your stance on demonic talking foxes?" , answer=="A life without demonic talking foxes is no life at all.")
	then
		String questiontext = "Lars Von Trier";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end


// Hugo: prawo, kurwa prawo

rule "Do you like creepy movies with a twist?"
	when
		q : Question(question == "Do you like your movies a little on the creepy side?" , answer=="I love creepy movies.")
	then
		String questiontext = "Do you like creepy movies with a twist?";
		String answer1 = "I am shameless sucker for a twist.";
		String answer2 = "Meh, a twist is completely unnecessary";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end


rule "M. Night Shyamalan"
	when
		q : Question(question == "Do you like creepy movies with a twist?" , answer=="I am shameless sucker for a twist.")
	then
		String questiontext = "M. Night Shyamalan";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you like animation?"
	when
		q : Question(question == "Do you like creepy movies with a twist?" , answer=="Meh, a twist is completely unnecessary")
	then
		String questiontext = "Do you like animation?";
		String answer1 = "What, like for kids? No thanks.";
		String answer2 = "Hell, yeah!";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Tim Burton"
	when
		q : Question(question == "Do you like animation?" , answer=="Hell, yeah!")
	then
		String questiontext = "Tim Burton";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you want to see things that no human should really ever see?"
	when
		q : Question(question == "Do you like animation?" , answer=="What, like for kids? No thanks.")
	then
		String questiontext = "Do you want to see things that no human should really ever see?";
		String answer1 = "Golly gee, I sure don't.";
		String answer2 = "The more disgusting the better.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Guillermo Del Toro"
	when
		q : Question(question == "Do you want to see things that no human should really ever see?" , answer=="Golly gee, I sure don't.")
	then
		String questiontext = "Guillermo Del Toro";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Takashi Miike"
	when
		q : Question(question == "Do you want to see things that no human should really ever see?" , answer=="The more disgusting the better.")
	then
		String questiontext = "Takashi Miike";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

//left -> up -> right


rule "What's your stance on demonic talking foxes?"
	when
		q : Question(question == "How do you feel about foreign directors?" , answer=="I love them.")
	then
		String questiontext = "What's your stance on demonic talkng foxes?";
		String answer1 = "I life without demonic talking foxes is no life at all.";
		String answer2 = "No thank you.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you like rain?"
	when
		q : Question(question == "What's your stance on demonic talkng foxes?" , answer=="No thank you.")
	then
		String questiontext = "Do you like rain?";
		String answer1 = "It's great.";
		String answer2 = "Nope.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "How do you feel about religion?"
	when
		q : Question(question == "Do you like rain?" , answer=="Nope.")
	then
		String questiontext = "How do you feel about religion?";
		String answer1 = "It's not for me.";
		String answer2 = "I am well-versed in religious texts.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Akira Kurosawa"
	when
		q : Question(question == "Do you like rain?" , answer=="It's great.")
	then
	String questiontext = "Akira Kurosawa";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Robert Bresson"
	when
		q : Question(question == "How do you feel about religion?" , answer=="I am well-versed in religious texts.")
	then
	String questiontext = "Robert Bresson";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Ingmat Bergman"
	when
		q : Question(question == "How do you feel about religion?" , answer=="It's not for me.")
	then
	String questiontext = "Ingmar Bergman";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you like loner white guys in your movies?"
	when
		q : Question(question == "How do you feel about foreign directors?" , answer=="I said I wanted to watch drama. Don't get carried away.")
	then
		String questiontext = "Do you like loner white guys in your movies?";
		String answer1 = "Not really.";
		String answer2 = "Loner white guys are awesome!";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Do you own a tin foll hat to keep the government from reading your mind when you go to Starbucks?"
	when
		q : Question(question == "Do you like loner white guys in your movies?" , answer=="Not really.")
	then
		String questiontext = "Do you own a tin foll hat to keep the government from reading your mind when you go to Starbucks?";
		String answer1 = "Nope.";
		String answer2 = "That way, they don't know how many lattes I have each year!";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "How much do you like New York?"
	when
		q : Question(question == "Do you like loner white guys in your movies?" , answer=="Loner white guys are awesome!")
	then
		String questiontext = "How much do you like New York?";
		String answer1 = "I love NY!";
		String answer2 = "Nothing against New York, but it's not necessary in my movies.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Martin Scorsese"
	when
		q : Question(question == "How much do you like New York?" , answer=="I love NY!")
	then
	String questiontext = "Martin Scorsese";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "David Fincher"
	when
		q : Question(question == "How much do you like New York?" , answer=="Nothing against New York, but it's not necessary in my movies.")
	then
	String questiontext = "David Fincher";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end


rule "Oliver Stone"
	when
		q : Question(question == "Do you own a tin foll hat to keep the government from reading your mind when you go to Starbucks?" , answer=="That way, they don't know how many lattes I have each year!")
	then
	String questiontext = "Oliver Stone";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "I prefer a director who has worked with..."
	when
		q : Question(question == "Do you own a tin foll hat to keep the government from reading your mind when you go to Starbucks?", answer=="Nope.")
	then
		String questiontext = "I prefer a director who has worked with...";
		String answer1 = "An orangutan.";
		String answer2 = "Don Knotts.";
		String answer3 = "";
		
		q.setQuestion(questiontext);
		update(q);
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Clint Eastwood"
	when
		q : Question(question == "I prefer a director who has worked with..." , answer=="An orangutan.")
	then
	String questiontext = "Clint Eastwood";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end

rule "Ron Howard"
	when
		q : Question(question == "I prefer a director who has worked with..." , answer=="Don Knotts.")
	then
	String questiontext = "Ron Howard";
		String answer1 = "";
		String answer2 = "";
		String answer3 = "";
		
		frame.setDisplayText(questiontext);
		frame.setButtonText(0,answer1);
		frame.setButtonText(1,answer2);
		frame.setButtonText(2,answer3);		
		frame.pack();
end


