package com.sample;

import javax.swing.JFrame;

global MyFrame frame;
 
declare Pytanie
	pytanie : String
	odpowiedz : String[]
	wybranaOdpowiedz : int
end

rule "default"
	when
	then
		
		Pytanie pytanie = new Pytanie( "Is a train going into a tunel ever just a train going into a tunel?",
							 new String[]{"Of course it's just a train going into a tunel. What else would it be?",
							 			  "No. It's always sexual and Freudian.",""} , 0);
		frame.setDisplayText(pytanie.getPytanie());
		for(int i = 0; i < 3; i++)
		{
			frame.setButtonText( i, pytanie.getOdpowiedz()[i]);
		}
		
		
		pytanie.setWybranaOdpowiedz(0);
		insert( pytanie );
end

rule "Of course it's just a train going into a tunel. What else would it be?"
	when
		
	then
end
 
rule "No. It's always sexual and Freudian."
	when
		
	then
end

